### ISSUE TITLE
Optimal number of topics

### ISSUE THREAD

**Issue by grassdew** [esproff/TopicModelsVB.jl#8]
Hi,

I wonder if there is a way to help determine the optimal number of topics? Thanks.

**Comment by esproff** [comment]
If you visit David Blei's page you'll see papers discussing Hierarchical Dirichlet Processes.

Basically there exist nonparametric topic models which can automatically find the "optimal" number of topics for a given corpus.  But implementing such a model in this package I felt would take me too far afield and would have led to the type of feature creep which I wasn't willing to fully commit to, so I decided not to implement any of them.

Other than that I think there might be certain metrics, such as _perplexity_ which can evaluate the quality of the topics, which you could use to compare the model across multiple topic numbers, however since the output is human interpretable, it's often just easier to try different numbers of topics and see what works best for yourself.

**Comment by grassdew** [comment]
Thanks for your comment. I will try different numbers of topics to determine how many I need.
